### create new token (admin)
POST http://localhost:8080/exam/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "qwer"
}

### Create conference
POST http://localhost:8080/exam/api/admin/post/conference
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NzQxMzY4NzQsImlhdCI6MTY3NDEzNTA3NCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.1dyZLEJYSF1Ouj5nMc5ussAznOfCPRYQuJ6YI7a7YcM

{
  "conferenceName": "http",
  "location": "http 11",
  "capacity": 55,
  "strDate": "2025-01-19",
  "talks": []
}
### Update Conference
PUT http://localhost:8080/exam/api/admin/put/conference
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NzQxNTQ1ODEsImlhdCI6MTY3NDE1Mjc4MSwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.wSpvxYnKt9EIGL4G9wGeSj4m3kjFBaDQ2ZpRi0IanQY

{
  "conferenceName": "Test1",
  "location": "her",
  "capacity": 1337,
  "strDate": "2025-12-12",
  "talks": [
    {
      "id": 2,
      "users": [
        {
          "userName": "nicki"
        }
      ]
    },
    {
      "id": 1,
      "users": [
        {
          "userName": "nicki"
        }
      ]
    }
  ]
}

### delete talk
DELETE http://localhost:8080/exam/api/admin/delete/talk/1
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NzQxNDI4MzMsImlhdCI6MTY3NDE0MTAzMywiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.BAnH7lPL-EEAQAcKz5uLS-RqVl2a2zVwp9M7oWJ6St8