### create new token (user)
POST http://localhost:8080/exam/api/login
Content-Type: application/json

{
  "username": "nicki",
  "password": "qwer"
}

### Get All speakers
GET http://localhost:8080/exam/api/user/all/speakers
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWNraSIsInJvbGVzIjoic3BlYWtlciIsImV4cCI6MTY3NDEzNjgwNCwiaWF0IjoxNjc0MTM1MDA0LCJpc3N1ZXIiOiJzZW1lc3RlcnN0YXJ0Y29kZS1kYXQzIiwidXNlcm5hbWUiOiJuaWNraSJ9.i4wWwTSSPonwzp574rtWXc3A3FXjMUEp3Gr7iAXiNkw

### Get All conferences
GET http://localhost:8080/exam/api/user/all/conferences
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWNraSIsInJvbGVzIjoic3BlYWtlciIsImV4cCI6MTY3NDEzNjgwNCwiaWF0IjoxNjc0MTM1MDA0LCJpc3N1ZXIiOiJzZW1lc3RlcnN0YXJ0Y29kZS1kYXQzIiwidXNlcm5hbWUiOiJuaWNraSJ9.i4wWwTSSPonwzp574rtWXc3A3FXjMUEp3Gr7iAXiNkw



#Gamle eksempler:
### POST boat
POST http://localhost:8080/practice/api/admin/boat
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NzM4MTYyNDMsImlhdCI6MTY3MzgxNDQ0MywiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.cvvNeDkDDF5YDXOoW_im0IpcYnZZ8S5rZvzPBJimEgE

{
  "brand": "testbrand",
  "make": "2023",
  "image": "www.test.dk"
}

### PUT boat
PUT http://localhost:8080/practice/api/admin/boat
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NzM4MTYyNDMsImlhdCI6MTY3MzgxNDQ0MywiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.cvvNeDkDDF5YDXOoW_im0IpcYnZZ8S5rZvzPBJimEgE

{
  "boatId": 29,
  "brand": "p",
  "make": "44",
  "image": "put",
  "harbourId": 3,
  "userNames": [
    "Bo Bobsen",
    "user"
  ]
}

### delete boat
DELETE http://localhost:8080/practice/api/admin/boat/29
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NzM4MTYyNDMsImlhdCI6MTY3MzgxNDQ0MywiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.cvvNeDkDDF5YDXOoW_im0IpcYnZZ8S5rZvzPBJimEgE