### create new token (user)
POST http://localhost:8080/exam/api/login
Content-Type: application/json

{
  "username": "nicki",
  "password": "qwer"
}

### Get All speakers
GET http://localhost:8080/exam/api/user/all/speakers
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWNraSIsInJvbGVzIjoic3BlYWtlciIsImV4cCI6MTY3NDEzNjgwNCwiaWF0IjoxNjc0MTM1MDA0LCJpc3N1ZXIiOiJzZW1lc3RlcnN0YXJ0Y29kZS1kYXQzIiwidXNlcm5hbWUiOiJuaWNraSJ9.i4wWwTSSPonwzp574rtWXc3A3FXjMUEp3Gr7iAXiNkw

### Get All conferences
GET http://localhost:8080/exam/api/user/all/conferences
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWNraSIsInJvbGVzIjoic3BlYWtlciIsImV4cCI6MTY3NDE3Njc0NSwiaWF0IjoxNjc0MTc0OTQ1LCJpc3N1ZXIiOiJzZW1lc3RlcnN0YXJ0Y29kZS1kYXQzIiwidXNlcm5hbWUiOiJuaWNraSJ9.zS6qujXumpYNnXM1mclXNvis_46k5UXtLcpT94a_IPo

### Get All conferences
GET http://localhost:8080/exam/api/user/talksBySpeaker/nicki
Content-Type: application/json
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWNraSIsInJvbGVzIjoic3BlYWtlciIsImV4cCI6MTY3NDE5MDMyOSwiaWF0IjoxNjc0MTg4NTI5LCJpc3N1ZXIiOiJzZW1lc3RlcnN0YXJ0Y29kZS1kYXQzIiwidXNlcm5hbWUiOiJuaWNraSJ9.3zj64WIlxN8qJAS5vCmwTcqTpmArQMSjwv65Xg8bjUk

